### ISSUE TITLE
NameError: name 'ipn_pbs_qsub' is not defined

### ISSUE THREAD

**Issue by Taylor95** [HaoKeLab/ensembleCNV#3]
Hello,
Thanks for your time. I have just got the package from Dr. Stephen W. Scherer. Then I tried to run iPattern and had this problem:

> ..........
NameError: name 'ipn_pbs_qsub' is not defined

I have run the command "ln -s .......". How to deal with the problem? Thanks.

**Comment by zhongyangzhang** [comment]
Thank you for your question. Based on your current description, we cannot locate where the problem is without further details. In our experiences, we run iPattern sequentially without "qsub". Please refer to the details about how we run iPattern at https://github.com/HaoKeLab/ensembleCNV/tree/master/01_initial_call/run_iPattern. We would also suggest you consult the authors of iPattern.

**Comment by Taylor95** [comment]
OK, thank you for your answering!



在 2019年1月30日，01:08，zhongyangzhang <notifications@github.com<mailto:notifications@github.com>> 写道：


Thank you for your question. Based on your current description, we cannot locate where the problem is without further details. In our experiences, we run iPattern sequentially without "qsub". Please refer to the details about how we run iPattern at https://github.com/HaoKeLab/ensembleCNV/tree/master/01_initial_call/run_iPattern. We would also suggest you consult the authors of iPattern.
